; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Yum Poc"
#define MyAppVersion "version beta"
#define MyAppPublisher "Yum Processos Operacionais Centrais Ltda."
#define MyAppURL "https://yum-poc.azurewebsites.net/"
#define MyAppExeName "YumSistema-1.0-SNAPSHOT-jar-with-dependencies.jar"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5BF9A000-881C-4B54-870F-B99295914A97}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\aluno\Desktop\YumPocLicense.txt
InfoBeforeFile=C:\Users\aluno\Desktop\BeforeInstallation.txt
InfoAfterFile=C:\Users\aluno\Desktop\AfterInstallation.txt
OutputDir=C:\Users\aluno\Desktop
OutputBaseFilename=YumInstaller
SetupIconFile=C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\Logo4.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\target\YumSistema-1.0-SNAPSHOT-jar-with-dependencies.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\logo6.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\Logo4.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\Logo4.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\Logo4.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

