; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BEFD5EDF-5DA7-4E98-BD20-24AEADDD071C}
AppName=YumPoc
AppVersion=Beta
;AppVerName=YumPoc Beta
AppPublisher=Yum Processos Operacionais Centrais Ltda.
AppPublisherURL=https://yum-poc.azurewebsites.net/
AppSupportURL=https://yum-poc.azurewebsites.net/
AppUpdatesURL=https://yum-poc.azurewebsites.net/
DefaultDirName={pf}\YumPoc
DisableProgramGroupPage=yes
OutputDir=C:\Users\aluno\Downloads
OutputBaseFilename=yumInstaller
SetupIconFile=C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\Logo4.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\target\YumSistema-1.0-SNAPSHOT-jar-with-dependencies.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\Logo6.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aluno\Desktop\yum-poc\YumSistema\Imagens\Logo4.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\YumPoc"; Filename: "{app}\Logo4.ico"
Name: "{commondesktop}\YumPoc"; Filename: "{app}\Logo4.ico"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\YumPoc"; Filename: "{app}\Logo4.ico"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\YumSistema-1.0-SNAPSHOT-jar-with-dependencies.jar"; Description: "{cm:LaunchProgram,YumPoc}"; Flags: shellexec postinstall skipifsilent

